# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Strip Comments

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Getting source
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Strip Comments
      run: |
        python ./utils/cleanup.py ./utils/input.css ./utils/output.conf

    - name: Upload back to repo
      run: |
        git config user.name ${{ secrets.GH_USER }}
        git config user.email ${{ secrets.GH_MAIL }}
        
        git add ./utils/output.conf
        git commit -m "Adding generated file by Github Workflow"
        git push
        